import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store,LOCK_MS} from '../src/store.js';
const password='A long private test passphrase 42';
async function setup(){const dir=mkdtempSync(join(tmpdir(),'lionmax-test-'));let now=Date.now();const path=join(dir,'db.sqlite');const store=new Store(path,{now:()=>now});const user=await store.register({username:'Test.Owner',name:'Test Owner',password});return{dir,path,store,user,advance:()=>{now+=LOCK_MS+1},clock:()=>now,close(){store.close();rmSync(dir,{recursive:true,force:true})}};}
test('all three credentials are required, generated token is seven alphanumeric characters, and storage excludes plaintext secrets',async()=>{const t=await setup();try{assert.match(t.user.token,/^[A-Za-z0-9]{7}$/);assert.equal((await t.store.authenticate(t.user.username,password,'wrong00')).ok,false);assert.equal((await t.store.authenticate(t.user.username,'wrong password',t.user.token)).ok,false);assert.equal((await t.store.authenticate(t.user.username,password,t.user.token)).ok,true);const row=t.store.getUser(t.user.id);assert.ok(row.password_hash.startsWith('$argon2id$'));assert.ok(row.token_hash.startsWith('$argon2id$'));assert.ok(!JSON.stringify(row).includes(t.user.token));assert.ok(!JSON.stringify(row).includes(password));}finally{t.close()}});
test('exactly five failures lock the account, including correct credentials, persist across restart, and expire after 15 minutes',async()=>{const t=await setup();try{for(let n=0;n<5;n++)assert.equal((await t.store.authenticate(t.user.username,password,'badcode')).ok,false);assert.equal(t.store.getUser(t.user.id).failures,5);assert.ok(t.store.getUser(t.user.id).locked_until>t.clock());assert.equal((await t.store.authenticate(t.user.username,password,t.user.token)).ok,false);const other=new Store(t.path,{now:t.clock});try{assert.equal((await other.authenticate(t.user.username,password,t.user.token)).ok,false);t.advance();assert.equal((await other.authenticate(t.user.username,password,t.user.token)).ok,true);assert.equal(other.getUser(t.user.id).failures,0)}finally{other.close()}}finally{t.close()}});
test('concurrent failures cannot bypass the fifth-attempt lock',async()=>{const t=await setup();try{await Promise.all(Array.from({length:12},()=>t.store.authenticate(t.user.username,password,'badcode')));assert.equal(t.store.getUser(t.user.id).failures,5);assert.equal((await t.store.authenticate(t.user.username,password,t.user.token)).ok,false)}finally{t.close()}});
test('IP usage counts both successful and failed attempts without storing the token',async()=>{const t=await setup();try{await t.store.authenticate(t.user.username,password,t.user.token,'::ffff:192.0.2.3');await t.store.authenticate(t.user.username,password,'badcode','192.0.2.3');await t.store.authenticate(t.user.username,password,t.user.token,'192.0.2.4');const rows=t.store.usage(t.user.id);const shared=rows.find(r=>r.ip==='192.0.2.3');assert.equal(shared.attempts,2);assert.equal(shared.successes,1);assert.equal(rows.length,2);assert.ok(!JSON.stringify(rows).includes(t.user.token));}finally{t.close()}});
test('profile and credential records survive sign-out and restart; sessions are revoked on token replacement',async()=>{const t=await setup();try{const session=t.store.createSession(t.user.id);t.store.updateName(t.user.id,'Retained Name');t.store.logout(session);assert.equal(t.store.session(session),null);const other=new Store(t.path);try{assert.equal(other.getUser(t.user.id).name,'Retained Name')}finally{other.close()};const active=t.store.createSession(t.user.id);const next=await t.store.rotateToken(t.user.id,password,t.user.token,'127.0.0.1');assert.match(next,/^[A-Za-z0-9]{7}$/);assert.equal(t.store.session(active),null);assert.equal((await t.store.authenticate(t.user.username,password,t.user.token)).ok,false);assert.equal((await t.store.authenticate(t.user.username,password,next)).ok,true)}finally{t.close()}});
test('unknown accounts do not authenticate and persistent connection throttling counts correctly',async()=>{const t=await setup();try{assert.equal((await t.store.authenticate('nobody',password,t.user.token)).ok,false);for(let i=0;i<5;i++)assert.equal(t.store.throttle('ip',5,1000),true);assert.equal(t.store.throttle('ip',5,1000),false);const other=new Store(t.path);try{assert.equal(other.throttle('ip',5,1000),false)}finally{other.close()}}finally{t.close()}});
test('OIDC adapter persists, consumes, expires and revokes protocol records',async()=>{const t=await setup();try{const Adapter=t.store.adapter(),adapter=new Adapter('AuthorizationCode');await adapter.upsert('test',{grantId:'g',accountId:t.user.id},60);assert.ok(await adapter.find('test'));await adapter.consume('test');assert.ok((await adapter.find('test')).consumed);await adapter.revokeByGrantId('g');assert.equal(await adapter.find('test'),undefined);await adapter.upsert('expired',{},1);t.advance();assert.equal(await adapter.find('expired'),undefined)}finally{t.close()}});
