import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
const executablePath = resolve('release/desktop/LionMax-win32-x64/LionMax.exe');
const data = mkdtempSync(join(tmpdir(), 'lionmax-desktop-test-'));
const env = { ...process.env, LIONMAX_DATA_DIR: data };
delete env.ELECTRON_RUN_AS_NODE;
let app;
await assert.rejects(fetch('http://127.0.0.1:4545/health'), 'Stop existing LionMax services before this isolated test');
try {
  app = await electron.launch({ executablePath, env });
  const page = await app.firstWindow();
  await page.getByRole('navigation', { name: 'LionMax navigation' }).waitFor();
  await page.screenshot({ path: 'artifacts/lionmax-desktop.png' });
  const prefs = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());
  assert.equal(prefs.nodeIntegration, false);
  assert.equal(prefs.contextIsolation, true);
  assert.equal(prefs.sandbox, true);
  await page.context().route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.getByRole('navigation').getByRole('link', { name: 'Create account', exact: true }).click();
  await page.getByRole('checkbox', { name: /Microsoft 365/ }).check();
  await page.getByRole('checkbox', { name: /Google Workspace/ }).check();
  assert.equal(await page.getByRole('checkbox', { name: /Slack/ }).count(), 1);
  await page.screenshot({ path: 'artifacts/lionmax-desktop-setup.png', fullPage: true });
  await page.getByLabel('Your name').fill('Desktop Test');
  await page.getByLabel('Choose a username').fill('desktop.test');
  await page.getByLabel('Create a password', { exact: true }).fill('Desktop test passphrase 123!');
  await page.getByRole('checkbox', {name: /I understand/}).check();
  await page.getByRole('button', { name: 'Create account' }).click();
  const token = await page.locator('#saved-token').textContent();
  assert.match(token, /^[A-Za-z0-9]{7}$/);
  await page.getByRole('link', { name: 'I saved my token. Continue' }).click();
  await page.getByLabel('Username', { exact: true }).fill('desktop.test');
  await page.getByLabel('Password', { exact: true }).fill('Desktop test passphrase 123!');
  await page.getByLabel('Personal token', { exact: true }).fill(token);
  await page.getByRole('button', { name: 'Sign in securely' }).click();
  await page.getByRole('heading', { name: 'Hello, Desktop Test.' }).waitFor();
  await page.getByRole('navigation').getByRole('link', { name: 'Connections', exact: true }).click();
  assert.equal(await page.getByText('Setup required · Selected for your account', { exact: true }).count(), 2);
  assert.equal(await page.getByRole('button', { name: 'Connect', exact: true }).count(), 3);
  for (const button of await page.getByRole('button', { name: 'Connect', exact: true }).all()) assert.equal(await button.isDisabled(), true);
  await page.getByLabel('Software or website name').fill('Company Portal');
  await page.getByLabel('Website address').fill('https://portal.example.com');
  await page.getByRole('button', { name: 'Add website' }).click();
  await page.getByRole('link', { name: 'Open website', exact: true }).waitFor();
  assert.ok(await page.locator('.saved-site > div').evaluate(el => el.getBoundingClientRect().width > 120));
  await page.screenshot({ path: 'artifacts/lionmax-desktop-connections.png', fullPage: true });
  const rejected = await page.context().request.post('http://127.0.0.1:4545/connections/websites/add', { form: { name: 'Injected', url: 'https://example.com', csrf: 'wrong' }, headers: { Origin: 'http://127.0.0.1:4545' } });
  assert.equal(rejected.status(), 403);
  await app.close(); app = null;
  await new Promise(r => setTimeout(r, 1200));
  await assert.rejects(fetch('http://127.0.0.1:4545/health'));
  app = await electron.launch({ executablePath, env });
  const second = await app.firstWindow();
  await second.getByLabel('Username', { exact: true }).fill('desktop.test');
  await second.getByLabel('Password', { exact: true }).fill('Desktop test passphrase 123!');
  await second.getByLabel('Personal token', { exact: true }).fill(token);
  await second.getByRole('button', { name: 'Sign in securely' }).click();
  await second.getByRole('heading', { name: 'Hello, Desktop Test.' }).waitFor();
  await second.getByRole('navigation').getByRole('link', { name: 'Connections', exact: true }).click();
  assert.equal(await second.getByText('Setup required · Selected for your account', { exact: true }).count(), 2);
  assert.equal(await second.getByRole('link', { name: 'Open website', exact: true }).getAttribute('href'), 'https://portal.example.com/');
  writeFileSync('artifacts/desktop-verification.json', JSON.stringify({ passed: true, checks: ['packaged EXE startup', 'desktop navigation', 'sandboxed renderer', 'registration and login with external renderer requests blocked', 'owned service shutdown', 'account persists after restart'] }, null, 2));
  console.log('PASS: packaged desktop startup, registration, login, shutdown and restart persistence');
} finally { await app?.close(); }
