import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import { randomBytes,createHash } from 'node:crypto';
import { jwtVerify,createRemoteJWKSet } from 'jose';
const issuer=process.env.LIONMAX_ISSUER||'http://127.0.0.1:4545';
const origin=process.env.LIONMAX_DEMO_ORIGIN||'http://127.0.0.1:4546';
const clientId=process.env.LIONMAX_CLIENT_ID||'lionmax-demo';
const callback=origin+'/callback';const pending=new Map(),sessions=new Map();
const app=express();app.use(helmet({contentSecurityPolicy:false,strictTransportSecurity:false}));app.use(cookieParser());app.use((_req,res,next)=>{res.set('Cache-Control','no-store');next()});
const random=()=>randomBytes(32).toString('base64url');const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts={httpOnly:true,sameSite:'lax',secure:origin.startsWith('https:'),path:'/'};
function html(title,body){return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Northstar</title><style>body{background:#edf0f5;color:#202a40;font:16px/1.7 Segoe UI,sans-serif;margin:0}main{max-width:640px;margin:10vh auto;padding:45px;background:white;border-radius:20px;box-shadow:0 20px 70px #27365b15}small{letter-spacing:3px;color:#626d87}h1{font-size:38px;line-height:1.2}a,button{display:inline-block;background:#243554;color:white;padding:13px 20px;border:0;border-radius:8px;text-decoration:none;font:inherit}p{color:#536078}code{word-break:break-all}footer{font-size:12px;color:#748098;margin-top:30px}@media(max-width:700px){main{margin:30px 15px;padding:28px}}</style><main><small>NORTHSTAR / INDEPENDENT DEMO APP</small>${body}<footer>This separate app never receives your LionMax password or personal token.</footer></main></html>`;}
let discovery,jwks;
async function metadata(){if(!discovery){const r=await fetch(issuer+'/.well-known/openid-configuration',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('LionMax is unavailable.');discovery=await r.json();if(discovery.issuer!==issuer)throw Error('Issuer mismatch');jwks=createRemoteJWKSet(new URL(discovery.jwks_uri));}return discovery;}
app.get('/health',(_req,res)=>res.json({service:'Northstar Demo',status:'ok'}));
app.get('/',(req,res)=>{const s=sessions.get(req.cookies.northstar_session);if(s&&s.expires>Date.now())return res.send(html('Connected',`<h1>Welcome, ${esc(s.claims.name||s.claims.preferred_username)}.</h1><p id="verified">Your identity was verified by LionMax.</p><p>Account: <code>${esc(s.claims.sub)}</code></p><p>Username: <strong>${esc(s.claims.preferred_username)}</strong></p><form method="post" action="/logout"><input type="hidden" name="csrf" value="${s.csrf}"><button>Sign out of Northstar</button></form>`));res.send(html('Sign in','<h1>A separate app.<br>The same identity.</h1><p>Use your LionMax account to enter Northstar. This demonstration runs on a different origin and verifies the response using OpenID Connect.</p><a href="/login">Sign in with LionMax ?</a>'));});
app.get('/login',async(req,res)=>{for(const [key,value]of pending)if(value.expires<Date.now())pending.delete(key);if(pending.size>1000)return res.sendStatus(429);const config=await metadata(),id=random(),state=random(),nonce=random(),verifier=random();pending.set(id,{state,nonce,verifier,expires:Date.now()+600_000});res.cookie('northstar_pending',id,{...opts,maxAge:600_000});const url=new URL(config.authorization_endpoint);url.search=new URLSearchParams({client_id:clientId,redirect_uri:callback,response_type:'code',scope:'openid profile',state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',prompt:'login'}).toString();res.redirect(url.toString());});
app.get('/callback',async(req,res)=>{const id=req.cookies.northstar_pending,attempt=pending.get(id);pending.delete(id);res.clearCookie('northstar_pending',opts);if(!attempt||attempt.expires<Date.now()||req.query.state!==attempt.state||typeof req.query.code!=='string')return res.status(400).send(html('Sign-in declined','<h1>Sign-in not completed.</h1><p>This request was canceled, expired or could not be verified.</p><a href="/">Start again</a>'));const config=await metadata();const response=await fetch(config.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:clientId,redirect_uri:callback,code:req.query.code,code_verifier:attempt.verifier}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Code exchange failed');const tokens=await response.json();const {payload}=await jwtVerify(tokens.id_token,jwks,{issuer,audience:clientId,algorithms:['RS256'],maxTokenAge:'5m'});if(payload.nonce!==attempt.nonce||!payload.sub)throw Error('Invalid identity response');const profileResponse=await fetch(config.userinfo_endpoint,{headers:{Authorization:`Bearer ${tokens.access_token}`},signal:AbortSignal.timeout(5000)});if(!profileResponse.ok)throw Error('Profile request failed');const profile=await profileResponse.json();if(profile.sub!==payload.sub)throw Error('Profile subject mismatch');for(const [key,value]of sessions)if(value.expires<Date.now())sessions.delete(key);const session=random();sessions.set(session,{claims:{...profile,sub:payload.sub},csrf:random(),expires:Date.now()+15*60_000});res.cookie('northstar_session',session,{...opts,maxAge:15*60_000});res.redirect('/');});
app.post('/logout',express.urlencoded({extended:false,limit:'2kb'}),(req,res)=>{const s=sessions.get(req.cookies.northstar_session);if(req.get('origin')!==origin||!s||s.csrf!==req.body.csrf)return res.sendStatus(403);sessions.delete(req.cookies.northstar_session);res.clearCookie('northstar_session',opts);res.redirect('/');});
app.use((err,_req,res,_next)=>{console.error('Demo authentication failed:',err.code||err.name);res.status(502).send(html('Connection unavailable','<h1>Unable to verify sign-in.</h1><p>Check that LionMax is running and start again.</p><a href="/">Return</a>'))});
app.listen(Number(new URL(origin).port||4546),'127.0.0.1',()=>console.log('Northstar demo ready at '+origin));
