import { escape, hidden, layout } from './views.js';
export function pluginPicker(plugins, selected = []) {
  return `<fieldset class="plugin-picker"><legend>Office connections <span class="optional">Optional</span></legend><p class="hint">Choose the accounts you use. You can connect them after saving your LionMax account.</p><div class="plugin-grid">${plugins.map(p => `<label class="plugin-choice"><input type="checkbox" name="plugins" value="${escape(p.id)}" ${selected.includes(p.id) ? 'checked' : ''}><span><strong>${escape(p.name)}</strong><small>${escape(p.description)}</small><small>${p.ready ? 'Ready to connect after sign-in' : 'Included · administrator setup required'}</small></span></label>`).join('')}</div><p class="hint">Proprietary software and websites can be added later in Connections.</p></fieldset>`;
}
export function connectionsPage({ plugins, selected, identities, websites, grants, csrf, message = '' }) {
  return layout('Connections', `<h2>Connections</h2><p class="intro">Your office identities and websites, remembered with your LionMax account.</p>${message ? `<div class="notice" role="status">${escape(message)}</div>` : ''}<div class="connection-toolbar"><a class="secondary button-link" href="/connections">Refresh status</a><a href="/connections/setup">Connector setup</a></div><h3>Office accounts</h3><p class="hint">Connecting verifies your identity. It does not grant access to mail, files or messages.</p><div class="connection-list">${plugins.map(p => {
    const linked = identities.find(i => i.plugin_id === p.id);
    return `<section class="connection-card"><div class="connection-icon" aria-hidden="true">${escape(p.initials)}</div><div class="connection-copy"><h3>${escape(p.name)}</h3><p>${escape(p.description)}</p><span class="connection-status ${linked ? 'connected' : ''}">${linked ? 'Connected' : p.ready ? 'Ready to connect' : 'Setup required'}${selected.includes(p.id) ? ' · Selected for your account' : ''}</span>${linked ? `<p>${escape(linked.name || linked.email || 'Verified account')}</p>` : !p.ready ? `<p class="hint">${escape(p.issue)}</p>` : ''}</div><form method="post" action="/connections/${escape(p.id)}/${linked ? 'remove' : 'start'}">${hidden(csrf)}<button class="secondary" ${!linked && !p.ready ? 'disabled' : ''}>${linked ? 'Disconnect' : 'Connect'}</button></form></section>`;
  }).join('')}</div><details><summary>Change setup selections</summary><form method="post" action="/connections/preferences">${hidden(csrf)}${pluginPicker(plugins, selected)}<button class="secondary">Save selections</button></form></details><h3>Your software & websites</h3><p class="hint">Save your company portal, CRM, payroll or another website. Saved links use the website’s own sign-in until its administrator integrates LionMax.</p>${websites.map(w => `<section class="saved-site"><div><strong>${escape(w.name)}</strong><small>${escape(w.url)}</small></div><a class="secondary button-link" data-external href="${escape(w.url)}">Open website</a><form method="post" action="/connections/websites/remove">${hidden(csrf)}<input type="hidden" name="id" value="${escape(w.id)}"><button class="text-button">Remove</button></form></section>`).join('') || '<p class="hint">No websites saved yet.</p>'}<form class="website-form" method="post" action="/connections/websites/add">${hidden(csrf)}<label for="website-name">Software or website name</label><input id="website-name" name="name" maxlength="80" placeholder="Company portal" required><label for="website-url">Website address</label><input id="website-url" name="url" type="url" maxlength="2048" placeholder="https://portal.your-company.com" required><button class="secondary">Add website</button></form><h3>Websites using your LionMax identity</h3><p class="hint">These websites have received your consent to sign in using LionMax. Removing access revokes LionMax grants; an existing website session may remain until it expires.</p>${grants.map(g => `<section class="saved-site"><strong>${escape(g.name)}</strong><form method="post" action="/connections/grants/remove">${hidden(csrf)}<input type="hidden" name="id" value="${escape(g.id)}"><button class="secondary">Remove access</button></form></section>`).join('') || '<p class="hint">No connected websites yet. Your software developer can add LionMax sign-in using the integration guide.</p>'}<a href="/developers">Custom software integration guide</a>`, { wide: true });
}
export function connectorSetup(plugins) {
  return layout('Connector setup', `<h2>Connector setup</h2><p class="intro">Microsoft 365, Google Workspace, Slack and custom OpenID Connect support are built into this program.</p><div class="prose"><p>Your organization’s administrator registers LionMax with each provider and adds the issued configuration to the local <code>plugins.json</code> file. Provider passwords are never entered into LionMax.</p><p>Microsoft requires a client ID and tenant ID. Google requires a Desktop app client ID. Slack requires a client ID, server-side secret and an HTTPS callback, so a local-only installation needs an administrator-managed HTTPS service before Slack can connect.</p><p>The included <code>docs/plugins.example.json</code> and <code>docs/CONNECTORS.md</code> describe configuration. For custom software, add a named OpenID Connect connector or integrate the software with LionMax sign-in.</p><p>External authorization opens the provider in your system browser. After approval, return to LionMax and refresh Connections. Account selections and linked identities stay in your local user database.</p></div><h3>Included connectors</h3>${plugins.map(p => `<p><strong>${escape(p.name)}</strong> — ${p.ready ? 'Configured' : escape(p.issue)}</p>`).join('')}<a href="/connections">Back to Connections</a>`, { wide: true });
}
