import { layout, escape, field, hidden, codesPanel } from './views.js';
const clientLabel = value => { const client = /Electron\//.test(value) ? 'LionMax desktop' : /Edg\//.test(value) ? 'Microsoft Edge' : /Firefox\//.test(value) ? 'Firefox' : /Chrome\//.test(value) ? 'Chrome' : 'Web browser'; const platform = /Windows/.test(value) ? 'Windows' : /Android/.test(value) ? 'Android' : /iPhone|iPad/.test(value) ? 'iOS' : /Macintosh/.test(value) ? 'macOS' : /Linux/.test(value) ? 'Linux' : 'this device'; return client+' on '+platform; };
const time = value => escape(new Date(value).toLocaleString('en-US',{timeZone:'UTC'}))+' UTC';
const formButton = (action,csrf,id,label) => `<form method="post" action="${action}">${hidden(csrf)}<input type="hidden" name="id" value="${escape(id)}"><button class="secondary">${label}</button></form>`;
export function recoveryPage(csrf,error='') {
 return layout('Recover account',`<span class="eyebrow">A WAY BACK IN</span><h2>Recover your account.</h2><p class="intro">Use one of the recovery codes you saved earlier. This replaces your password and personal token, signs out LionMax sessions, and replaces all old recovery codes.</p>${error?`<p class="notice error" role="alert">${escape(error)}</p>`:''}<form method="post" action="/recover">${hidden(csrf)}${field('username','Username','text','autocomplete="username" maxlength="32"')}${field('recovery','Recovery code','password','autocomplete="off" maxlength="64" spellcheck="false"')}${field('password','New password','password','autocomplete="new-password" minlength="15" maxlength="128"')}${field('confirmation','Confirm new password','password','autocomplete="new-password" minlength="15" maxlength="128"')}<button class="primary">Recover account</button></form><p class="hint">No saved code? Sign in with your existing credentials and create codes in Security. A username alone cannot recover an account.</p><a href="/login">Return to sign in</a>`);
}
export function recoveryCodesPage(username,codes) {
 return layout('Save recovery codes',`<span class="eyebrow">SAVE ONCE. KEEP PRIVATE.</span><h2>Your recovery codes.</h2><p class="intro">For <strong id="saved-username">${escape(username)}</strong>. These replace every previous recovery code. Anyone with a code and your username can reset your account.</p>${codesPanel(codes)}<a class="primary" href="/security">I saved my recovery codes</a>`,{wide:true});
}
export function securityPage(user,data,connections,csrf,currentId,message='') {
 const grants=connections.grants(user.id), identities=connections.identities(user.id);
 const labels={'login.success':'Signed in','login.failed':'Failed sign-in','login.locked':'Account temporarily locked','session.auto_locked':'Session automatically locked','session.revoked':'Session revoked','sessions.revoked':'All sessions signed out','device.locked':'Windows lock or sleep','account.recovered':'Account recovered','recovery.failed':'Recovery attempt rejected','recovery.codes.created':'Recovery codes replaced','settings.updated':'Auto-lock settings updated','token.replaced':'Personal token replaced','account.created':'Account created','profile.updated':'Profile updated','connection.linked':'Provider linked','connection.removed':'Provider removed','connection.grant.revoked':'Application access revoked'};
 return layout('Security dashboard',`<div class="panel-top"><span class="eyebrow">YOUR IDENTITY. YOUR CONTROL.</span><span class="badge">SECURITY</span></div><h2>Security dashboard</h2><p class="intro">Your sign-ins, recovery options, and application access in one place.</p>${message?`<p class="notice" role="status">${escape(message)}</p>`:''}<div class="security-stats"><div><strong>${data.sessions.length}</strong><span>Active sessions</span></div><div><strong>${data.codes}</strong><span>Recovery codes</span></div><div><strong>${grants.length+identities.length}</strong><span>App connections</span></div></div><div class="section-links"><a href="/account">My account</a><a href="/connections">Connections</a><a href="/appearance">Access &amp; appearance</a></div>
 <h3>Automatic locking</h3><form method="post" action="/security/settings">${hidden(csrf)}<label for="idle_minutes">Lock after inactivity</label><select id="idle_minutes" name="idle_minutes">${[1,5,10,15,30].map(n=>`<option value="${n}" ${n===data.settings.idle_minutes?'selected':''}>${n} minute${n===1?'':'s'}</option>`).join('')}</select><p class="hint">The desktop also locks when Windows locks or sleeps. Locking requires all three sign-in credentials again. External apps may keep their own sessions.</p><button class="secondary">Save auto-lock settings</button></form>${formButton('/lock',csrf,'','Lock now')}
 <h3>Recovery codes</h3><p class="hint">${data.codes?'You have saved-code recovery enabled. Generating new codes invalidates the old set.':'Recovery is not set up. Generate codes now so a lost password or personal token does not lock you out.'}</p><details><summary>Generate or replace recovery codes</summary><form method="post" action="/security/recovery">${hidden(csrf)}${field('password','Current password','password','autocomplete="current-password" maxlength="128"')}${field('token','Current personal token','password','autocomplete="off" minlength="7" maxlength="7"')}<button class="primary">Generate recovery codes</button></form></details>
 <h3>Active LionMax sessions</h3><div class="security-list">${data.sessions.map(s=>`<article class="security-item"><div><strong>${s.id===currentId?'This session':'Other session'}</strong><p>${escape(s.ip)} &middot; Last activity ${time(s.last_seen)}</p><p class="hint">${escape(clientLabel(s.agent))}</p></div>${formButton('/security/sessions/revoke',csrf,s.id,s.id===currentId?'Sign out here':'Revoke session')}</article>`).join('')||'<p>No active sessions.</p>'}</div>${formButton('/security/sessions/revoke-all',csrf,'','Sign out all sessions')}<p class="hint">Signing out all sessions also revokes LionMax authorization grants. Connected applications control their own existing sessions and signed tokens may remain valid until expiry.</p>
 <h3>Connected applications</h3><div class="security-list">${grants.map(g=>`<article class="security-item"><strong>${escape(g.name)}</strong>${formButton('/security/grants/revoke',csrf,g.id,'Revoke access')}</article>`).join('')}${identities.map(i=>`<article class="security-item"><div><strong>${escape(i.plugin_id)}</strong><p>${escape(i.name||i.email)}</p></div><a href="/connections">Manage provider</a></article>`).join('')}${!grants.length&&!identities.length?'<p class="hint">No connected applications yet.</p>':''}</div>
 <h3>Recent sign-in attempts</h3><div class="table-wrap"><table><thead><tr><th>Result</th><th>Connection</th><th>Time</th></tr></thead><tbody>${data.attempts.map(a=>`<tr><td>${a.success?'Accepted':'Rejected'}</td><td>${escape(a.ip)}</td><td>${time(a.at)}</td></tr>`).join('')||'<tr><td colspan="3">No attempts yet.</td></tr>'}</tbody></table></div><p class="hint">Most recent 30 attempts. IP addresses identify connections, not precise locations.</p>
 <h3>Security history</h3><ol class="event-list">${data.events.map(e=>`<li><span>${escape(labels[e.event]||e.event)}</span><time>${time(e.at)}</time></li>`).join('')}</ol>`,{wide:true});
}
export function appearancePage() {
 return layout('Access & appearance',`<span class="eyebrow">MAKE IT YOURS</span><h2>Access &amp; appearance</h2><p class="intro">Make LionMax easier to read and navigate. These choices are saved on this device, including the sign-in screen.</p><form id="appearance-form" data-local-form><label for="accent">Accent color</label><select id="accent" name="accent"><option value="cyan">Electric cyan</option><option value="violet">Soft violet</option><option value="amber">Warm amber</option></select><label for="text-size">Text size</label><select id="text-size" name="size"><option value="normal">Standard</option><option value="large">Large</option><option value="largest">Extra large</option></select><label class="check"><input type="checkbox" name="contrast"><span>High contrast</span></label><label class="check"><input type="checkbox" name="motion"><span>Reduce motion and decorative effects</span></label><div class="appearance-preview"><span class="eyebrow">PREVIEW</span><h3>A clearer view.</h3><p>Readable text, visible focus, and controls that work with your keyboard.</p><button type="button" class="secondary">Example control</button></div><button class="primary" type="submit">Save appearance</button><button class="secondary" type="button" id="reset-appearance">Reset to defaults</button><p id="appearance-status" role="status" aria-live="polite"></p></form><h3>Keyboard access</h3><p class="hint">Use Tab and Shift+Tab to move between controls, Enter to activate buttons, and the Skip to content link to bypass navigation. Auto-lock settings are in your Security dashboard.</p><a href="/security">Open Security dashboard</a>`,{wide:true});
}
