import { healthProof, requireHost, maintain } from './reliability.js';
import { installConnections } from './connections-routes.js';
import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { rateLimit } from 'express-rate-limit';
import Provider, { interactionPolicy } from 'oidc-provider';
import { fileURLToPath } from 'node:url';
import { join,dirname } from 'node:path';
import { Store } from './store.js';
import { issuer,port,dataDir,production,secrets } from './config.js';
import * as view from './views.js';
const root=dirname(dirname(fileURLToPath(import.meta.url))),keys=secrets();
const store=new Store(join(dataDir,'lionmax.sqlite'));
const demoOrigin=process.env.LIONMAX_DEMO_ORIGIN||'http://127.0.0.1:4546';
if(!production)store.db.prepare('INSERT OR IGNORE INTO clients VALUES(?,?)').run('lionmax-demo',JSON.stringify({client_id:'lionmax-demo',client_name:'Northstar Demo',redirect_uris:[demoOrigin+'/callback'],response_types:['code'],grant_types:['authorization_code'],token_endpoint_auth_method:'none',application_type:'web'}));
const policy=interactionPolicy.base();
policy.get('login').checks.add(new interactionPolicy.Check('lionmax_credentials','LionMax credentials are required','login_required',ctx=>!ctx.oidc.result?.login));
const provider=new Provider(issuer,{
 adapter:store.adapter(),clients:store.db.prepare('SELECT metadata FROM clients').all().map(r=>JSON.parse(r.metadata)),jwks:keys.jwks,
 cookies:{keys:keys.cookies,long:{sameSite:'lax'},short:{sameSite:'lax'}},
 interactions:{policy,url:(_ctx,interaction)=>'/interaction/'+interaction.uid},
 features:{devInteractions:{enabled:false},revocation:{enabled:true}},
 pkce:{required:()=>true},
 claims:{openid:['sub'],profile:['name','preferred_username']},
 ttl:{AccessToken:300,AuthorizationCode:60,IdToken:300,Interaction:600,Session:1800,Grant:86400},
 findAccount:async(_ctx,id)=>{const user=store.getUser(id);return user?{accountId:user.id,claims:async()=>({sub:user.id,name:user.name,preferred_username:user.username})}:undefined},
 renderError:async(ctx)=>{ctx.type='html';ctx.body=view.layout('Request could not be completed','<h2>Unable to continue.</h2><p class="intro">The sign-in request is invalid, expired, or not allowed. Return to the application and start again.</p><a href="/login">Back to LionMax</a>')}
});
const app=express();app.disable('x-powered-by');app.use(requireHost(issuer));
if(process.env.LIONMAX_TRUST_PROXY){app.set('trust proxy',process.env.LIONMAX_TRUST_PROXY.split(',').map(v=>v.trim()));provider.proxy=true;}
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'"],formAction:["'self'",...new Set(store.db.prepare('SELECT metadata FROM clients').all().flatMap(r=>JSON.parse(r.metadata).redirect_uris.map(u=>new URL(u).origin)))],frameAncestors:["'none'"],upgradeInsecureRequests:production?[]:null}},strictTransportSecurity:production?undefined:false}));
app.use(rateLimit({windowMs:60_000,limit:180,standardHeaders:'draft-8',legacyHeaders:false}));
app.use(cookieParser());
app.use((_req,res,next)=>{res.set('Cache-Control','no-store');res.set('Referrer-Policy','same-origin');next();});
app.use(express.static(join(root,'public'),{maxAge:0}));
const form=express.urlencoded({extended:false,limit:'8kb'});
const cookie={httpOnly:true,sameSite:'lax',secure:issuer.startsWith('https:'),path:'/'};
function csrf(req,res){const current=req.cookies.lionmax_csrf;if(typeof current==='string'&&/^[a-f0-9]{64}$/.test(current))return current;const token=view.csrfValue();res.cookie('lionmax_csrf',token,cookie);return token;}
function checkForm(req,res,next){if(req.get('origin')!==issuer||!view.same(req.cookies.lionmax_csrf,req.body.csrf))return res.status(403).send(view.layout('Request expired','<h2>Start again.</h2><p class="intro">This form could not be verified. Reload the sign-in page and try again.</p><a href="/login">Return to sign in</a>'));next();}
function limited(req,res,next){if(!store.throttle('login:'+req.ip,30,15*60_000))return res.status(429).send(view.layout('Try later','<h2>Please wait.</h2><p class="intro">Too many attempts from this connection. Try again in 15 minutes.</p>'));next();}
function signedIn(req,res,next){req.user=store.session(req.cookies.lionmax_session);if(!req.user)return res.redirect('/login');next();}
const {connections,catalog,ids:pluginIds}=installConnections(app,{store,dataDir,issuer,form,csrf,checkForm,signedIn});
const failure='Credentials not accepted. Check all three fields. After five failed attempts, wait 15 minutes before trying again.';
app.get('/health',(req,res)=>{healthProof(req,res);store.db.prepare('SELECT 1').get();res.json({status:'ok',service:'LionMax Universal Logon',version:'0.3.0'});});
app.get('/',(req,res)=>res.redirect(store.session(req.cookies.lionmax_session)?'/account':'/login'));
app.get('/login',(req,res)=>res.send(view.login({csrf:csrf(req,res)})));
app.post('/login',form,checkForm,limited,async(req,res)=>{const result=await store.authenticate(req.body.username,req.body.password,req.body.token,req.ip);if(!result.ok)return res.status(401).send(view.login({csrf:csrf(req,res),error:failure}));store.logout(req.cookies.lionmax_session);res.cookie('lionmax_session',store.createSession(result.user.id),{...cookie,maxAge:30*60_000});res.redirect(303,'/account');});
app.get('/register',(req,res)=>res.send(view.register(csrf(req,res),'',catalog)));
app.post('/register',form,checkForm,async(req,res)=>{if(!store.throttle('register:'+req.ip,5,60*60_000))return res.status(429).send(view.register(csrf(req,res),'Too many registrations from this connection. Try later.',catalog));try{if(req.body.accepted!=='yes')throw Error('Please acknowledge the token and activity-recording notice.');const choices=req.body.plugins===undefined?[]:Array.isArray(req.body.plugins)?req.body.plugins:[req.body.plugins];if(choices.length>100||choices.some(id=>!pluginIds.includes(id)))throw Error('Choose a listed connector.');const account=await store.register({...req.body,selectedPlugins:choices});res.status(201).send(view.tokenPage(account.token,account.username));}catch(e){if(e.status||e.code)throw e;res.status(400).send(view.register(csrf(req,res),e.message,catalog));}});
app.get('/account',signedIn,(req,res)=>res.send(view.account(req.user,store.usage(req.user.id),csrf(req,res))));
app.post('/account/profile',form,checkForm,signedIn,(req,res)=>{try{store.updateName(req.user.id,req.body.name);res.redirect(303,'/account');}catch(e){res.status(400).send(view.account(req.user,store.usage(req.user.id),csrf(req,res),e.message));}});
app.post('/account/token',form,checkForm,signedIn,limited,async(req,res)=>{try{const token=await store.rotateToken(req.user.id,req.body.password,req.body.token,req.ip);res.clearCookie('lionmax_session',cookie);res.send(view.tokenPage(token,req.user.username));}catch(e){res.status(400).send(view.account(req.user,store.usage(req.user.id),csrf(req,res),e.message));}});
app.post('/logout',form,checkForm,(req,res)=>{store.logout(req.cookies.lionmax_session);res.clearCookie('lionmax_session',cookie);res.redirect(303,'/login');});
app.get('/interaction/:uid',async(req,res)=>{const interaction=await provider.interactionDetails(req,res);const client=await provider.Client.find(interaction.params.client_id);if(interaction.prompt.name==='login')return res.send(view.login({csrf:csrf(req,res),action:`/interaction/${interaction.uid}/login`,client:client.clientName||client.clientId}));if(interaction.prompt.name!=='consent')return res.status(400).send('Unsupported interaction');res.send(view.layout('Connect application',`<span class="eyebrow">YOU ARE IN CONTROL</span><h2>Connect to ${view.escape(client.clientName||client.clientId)}?</h2><p class="intro">This application requests ${view.escape(interaction.params.scope)}. LionMax shares your account identifier and, if requested, your name and username. Your password, personal token and IP history are never shared.</p><form method="post" action="/interaction/${view.escape(interaction.uid)}/confirm">${view.hidden(csrf(req,res))}<button class="primary">Allow connection &rarr;</button></form><form method="post" action="/interaction/${view.escape(interaction.uid)}/abort">${view.hidden(csrf(req,res))}<button class="text-button">Cancel</button></form>`));});
app.post('/interaction/:uid/login',form,checkForm,limited,async(req,res)=>{const interaction=await provider.interactionDetails(req,res);if(interaction.prompt.name!=='login')return res.sendStatus(400);const result=await store.authenticate(req.body.username,req.body.password,req.body.token,req.ip);if(!result.ok){const client=await provider.Client.find(interaction.params.client_id);return res.status(401).send(view.login({csrf:csrf(req,res),action:`/interaction/${interaction.uid}/login`,error:failure,client:client.clientName||client.clientId}));}await provider.interactionFinished(req,res,{login:{accountId:result.user.id,amr:['pwd','lionmax_token']}},{mergeWithLastSubmission:false});});
app.post('/interaction/:uid/confirm',form,checkForm,async(req,res)=>{const details=await provider.interactionDetails(req,res);if(details.prompt.name!=='consent')return res.sendStatus(400);let grant=details.grantId?await provider.Grant.find(details.grantId):new provider.Grant({accountId:details.session.accountId,clientId:details.params.client_id});const missing=details.prompt.details;if(missing.missingOIDCScope)grant.addOIDCScope(missing.missingOIDCScope.join(' '));if(missing.missingOIDCClaims)grant.addOIDCClaims(missing.missingOIDCClaims);const grantId=await grant.save();await provider.interactionFinished(req,res,{consent:{grantId}},{mergeWithLastSubmission:true});});
app.post('/interaction/:uid/abort',form,checkForm,async(req,res)=>{await provider.interactionDetails(req,res);await provider.interactionFinished(req,res,{error:'access_denied',error_description:'Connection declined.'},{mergeWithLastSubmission:false});});
app.get('/help',(_req,res)=>res.send(view.layout('Sign-in help','<h2>Let’s get you unstuck.</h2><div class="prose"><p>Check your username, password, and case-sensitive seven-character token. Password-manager paste is supported.</p><p>After five failures, the account stays locked for 15 minutes, even with correct credentials. Further requests do not lengthen that lock.</p><p>If you lost your password or token, this release has no self-service recovery. Your deployment operator must establish a verified recovery process; a username or IP address alone cannot recover an account.</p><a href="/login">Return to sign in &rarr;</a></div>')));
app.get('/privacy',(_req,res)=>res.send(view.layout('Privacy & security','<span class="eyebrow">CLEAR BY DESIGN</span><h2>Your data, explained.</h2><div class="prose"><p>LionMax stores your username, display name and one-way password/token hashes. It never logs the reusable token itself.</p><p>Token verification attempts for an existing account record the observed IP address, time and whether sign-in succeeded. Your security history groups attempts by exact IP for 90 days. IPs can change, and multiple people can share one. These are connection records, not GPS or proof of physical location.</p><p>Profiles remain saved through sign-out, failed attempts, lockouts and application restarts. Your deployment operator controls the database and backups. Contact that operator for export or deletion requests.</p><p>Essential cookies protect forms and maintain sessions. Connected apps receive only approved identity claims, never your token or IP history.</p><p>A reusable typed code can be copied or phished. LionMax’s personal-token check is not advertised as phishing-resistant MFA.</p></div>',{wide:true})));
app.get('/developers',(_req,res)=>res.send(view.layout('Developer integration',`<span class="eyebrow">BUILT TO CONNECT</span><h2>A sign-in your app can use.</h2><div class="prose"><p>Register your application with the LionMax operator, then use OpenID Connect Authorization Code with PKCE (S256). Registration is controlled by the operator.</p><p>Discovery document:</p><pre>${view.escape(issuer)}/.well-known/openid-configuration</pre><p>Request <code>openid profile</code>. Validate the ID token’s signature, issuer, audience, expiration and nonce. Keep the authorization state tied to the initiating browser. Client apps never collect LionMax passwords or personal tokens.</p><p>Web, desktop and mobile apps must explicitly integrate LionMax. Each authorization requires fresh credential entry. Third-party applications control their own permissions and sessions.</p>${production?'':`<a class="primary button-link" href="${view.escape(demoOrigin)}">Open Northstar demo &rarr;</a>`}</div>`,{wide:true})));
app.use(provider.callback());
app.use((err,_req,res,_next)=>{console.error('Request failed:',err.code||err.name);if(res.headersSent)return;const status=err.status===413?413:err.status===503||(err.errcode===5||err.code?.includes('SQLITE_BUSY'))?503:500;if(status===503)res.set('Retry-After','3');res.status(status).send(view.layout('Unable to continue',`<h2>${status===503?'Please try again shortly.':'Unable to continue.'}</h2><p class="intro">${status===503?'LionMax is handling another operation. Wait a moment, then try again.':status===413?'This request is too large. Return to the form and try again.':'Your saved account data has been preserved. Return to the previous screen and try again.'}</p><a href="/login">Return to sign in</a>`));});
const server=app.listen(port,process.env.LIONMAX_BIND||'127.0.0.1',()=>console.log(`LionMax Universal Logon ready at ${issuer}`));
server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
const stopMaintenance=maintain(store,dataDir);let shuttingDown=false;
function shutdown(){if(shuttingDown)return;shuttingDown=true;server.close(async()=>{await stopMaintenance();store.close();process.exit(0)});server.closeIdleConnections();setTimeout(()=>process.exit(1),5000).unref();}
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,shutdown);
process.on('message',message=>{if(message?.type==='lionmax:shutdown')shutdown();});

if(process.connected)process.on('disconnect',shutdown);
